version: "3"
services:

  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "1111:8080"
      - "1000:1000"
    container_name: jenkins
    
    volumes: 
      - /home/apps/jenkins:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    links:
      - artifactory 
  artifactory:
    image: mattgruter/artifactory
    ports:
      - "9090:8080"
    container_name: artifactory
    volumes: 
      - /home/apps/artifactory:/artifactory:rw
