version: "3"
services:
  jenkins:
    image: jenkinsci/jenkins
    ports:
      - "8080:8080"
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home:rw

  sonarqube:
    image: sonarqube:6.7-alpine
    ports:
      - 9000:9000
    container_name: sonarqube
